### PR TITLE
Fix dangling apphosts

### PR DESCRIPTION
**Pull request by adrianbanks**
When the AppHost process is launched from certain shells (e.g. SSMS 2008), the AppHost process is left hanging around after SSMS is closed. This change introduces an option that, when specified, will launch a polling thread that will monitor for the presence of the parent process. If the parent process goes away, the AppHost process will be terminated also. This fixes bug PP-3683.

### CODE REVIEW

**Comment by clivetong** [comment]
You might be able to avoid starting your own thread by using the Exited event which uses the thread pool waiting mechanism.

var process = Process.GetProcessById(13360);
            process.EnableRaisingEvents = true;
            process.Exited += delegate
            {
                Console.WriteLine();
            };

**Comment by adrianbanks** [comment]
@clivetong  :+1:  Just tested this and it does work, so I'll update the code. Nice suggestion.

**Comment by adrianbanks** [comment]
@kevfromireland Could you take a look at this and see if you can spot any potential issues?

**Comment by kevfromireland** [comment]
Looks good to me, and I'm happy if you guys merge this. Two questions though:

1. Do we know why the Job support isn't kicking in for SSMS 2008? Did @DavidSimnerRG see this with the original Deployment Manager plugin that AppHost is based on?
2. Should we avoid the `GetParentProcessId` complication, and possible race, but just making it a requirement that the parent provides its own PID when starting the child?

**Comment by adrianbanks** [comment]
To answer your questions:

1. The problem isn't with the job code in AppHost. When running in SSMS 2008, SSMS makes a job which contains itself *and* the AppHost processes. The job has the Breakway setting instead of Kill On Job Close, meaning that when SSMS closes, the AppHost processes hang around.

SSMS 2008 R2 and upwards don't display this behaviour because they make a job that only contains the AppHost processes (i.e. doesn't contain the SSMS process). The job has Kill On Job Close set. The SSMS process keeps the handle to the job, so when SSMS closes so do the AppHost processes.

2. To do it this way would require SSMS to pass AppHost its process id, which it doesn't do.

**Comment by kevfromireland** [comment]
There are two components to AppHost though if I recall correctly, a portion that runs in-process with SSMS and a portion that runs out of process.

For both of my points this matters:

1. SSMS, or rather the Microsoft code in SSMS, isn't creating _any_ job...it is our code running within the SSMS process that is creating the job so are we just doing it wrong for SSMS2008?
2. We control both sides of this equation though so I'm not sure why we can't just add that you need to pass the PID as well. We are adding the requirement to pass `-m` to get this behaviour at all, why not make it that you pass `-m <pid>`

I'm pretty happy for this to go as-is, but more code that can go wrong and implementing 2, or better yet understanding 1 and removing the need for this code at all reduces the surface area of AppHost which was always designed to be incredibly small.

**Comment by adrianbanks** [comment]
After more digging, the issue of dangling AppHost processes only happens on versions of Windows *below* Windows 8. This is due to SSMS already being in a job when it starts, so we don't attempt to do anything about putting the new processes in a job with the correct Kill On Job Close setting (as we can't nest jobs on these OS versions). The job has Breakaway already set, so the processes remain when SSMS is closed.

I've done @kevfromireland's suggested change of passing in the host process id - makes the code much nicer.

**Comment by kevfromireland** [comment]
Happier now, but I do think we don't fully understand the issue.

Is it the specific combination of only SSMS2008 and Windows < 8?

Have we reproduced this when SSMS is started via Start Menu or only from the debugger, where the process tree might be a bit weird. 

In any case, I am pretty happy with this change, I just don't like not being able to explain why things are the way they are...

**Comment by adrianbanks** [comment]
> Is it the specific combination of only SSMS2008 and Windows < 8?

It seems to be, as it only happens with SSMS 2005 and 2008 on Windows < 8 (I was using Windows 7).

> Have we reproduced this when SSMS is started via Start Menu or only from the debugger, where the process tree might be a bit weird.

I was always using starting it from the Start menu, never the debugger.

> In any case, I am pretty happy with this change, I just don't like not being able to explain why things are the way they are...

Agreed, although I've ran out of ideas now as to find out why the job is being made in a different way with the combination of Windows and SSMS.

**Comment by kevfromireland** [comment]
Sounds good, merge, merge, merge!!

**Comment by clivetong** [comment]
Just in case you care, I wondered too where the job is created (we had such issues inside the profiler Addin) and after spending a while in windbg trapping the job object creation (when devenv runs) without success I read this post - http://stackoverflow.com/questions/89791/how-to-stop-the-visual-studio-debugger-starting-my-process-in-a-job-object . It's the PCA that is setting up the job. If you make the registry keys as he describes, then indeed you don't get a job object (when running visual studio in my case)

**Pull request merged**
