### PR TITLE
Add 64-bit client

### PR DESCRIPTION
**Pull request by AndrewHunterRedGate**

### CODE REVIEW

**Comment by alastairs** [comment]
I know this is über-old and already merged, but I've just seen the code in the repo and I'm curious why this approach was taken rather than, e.g.

1. Building the client exe for AnyCPU
2. Changing the target Platform at build time

**Comment by AndrewHunterRedGate** [comment]
An AnyCPU client exe would be unable to run an x86 assembly on a 64-bit system.

**Comment by alastairs** [comment]
> An AnyCPU client exe would be unable to run an x86 assembly on a 64-bit system.

Because it would start as a 64-bit process? Do we have use cases where it makes sense to kick off a 32-bit process from a 64-bit process? I would have thought that if 64-bit were available, everything would want to be 64-bit. I understand the desire to kick off a 64-bit process from a 32-bit process, though. 

What about the second option, of changing the target platform at build time?

**Comment by AndrewHunterRedGate** [comment]
The use case this was added for was for specifically selecting the bitness to use to call a particular COM+ API.

AnyCPU is usually only native. The original client exe was x86. Changing it to AnyCPU would break any code that referenced an x86 assembly on that assumption: given that this was written to interface mainly with CEF and CEF is just such an assembly, it would be exactly the wrong thing to do.

Changing the target platform is annoying because a build now requires two passes with a manual change. The platform control is not displayed by default in Visual Studio. Automated build scripts need to be customised to run the two passes, and this means that the automated build has different behavior to the user build, producing errors. Finally, if the AnyCPU DLLs are built in both the x86 and x64 passes and the x86 component depends on them, then it ends up referring to DLLs that have since been rebuilt, which causes it to fail to launch due to a version mismatch.

We did things this way in ANTS. It was (and is) a pain in the butt.

Having two project files like this can also be a bit of a nuisance but it means that everything is only built once, dependencies are kept up to date and there's no chance of accidentally running an out-of-date build.

**Comment by jornh** [comment]
Yeah and ... sadly to "quote" from https://swimmingpooldotnet.wordpress.com/2014/11/08/cefsharp-example-wpf-getting-started/:

**Pull request merged**
