### PR TITLE
Increase timeout from 20s to 2 minutes.

### PR DESCRIPTION
**Pull request by cawhitworth**
We are seeing timeouts in APP on some slower machines. We may want to make this configurable in the future.

### CODE REVIEW

**Comment by kevfromireland** [comment]
This looks perfectly sensible to me, no need to make it configurable and if it fails too fast for APP then likely to fail too fast for other products as well.

I propose merging this. Any objection from team SOC @alastairs ?

**Comment by alastairs** [comment]
The only thing I can think of is that it *might* cause us to leave SSMS unresponsive while we're waiting for AppHost to spin up, preventing a user from, e.g., seeing the connection dialog. I don't think this will be the case - @GrahamTheCoder / @garethbragg, do you know?

**Comment by kevfromireland** [comment]
I can't remember this code super well, but that sounds like a bug in SOC if it is the case, a bug which AppHost might make easy to do but none of this waiting should be happening on the UI thread. Even in the 'fast' case of 2-3s, that is a crazy amount of time to block the UI thread.

**Comment by cawhitworth** [comment]
We used to block the UI thread in APP when starting up the out-of-process CEF, but that's now fixed - the slight wrinkle is that the call to CreateElement() still has to be on the UI thread, but I don't think this is where the majority of time is spend.

**Comment by GrahamTheCoder** [comment]
I'm pretty sure SOC blocks the UI thread in `ServerControl`.
An nice alternative would be to create an implementation of IChildProcessHandle which initializes on a separate thread, and proxies the created handle. That way we can ninject bind the proxy `IChildProcessHandle` directly even while it's initializing. A less neat way of doing this would be to bind `Lazy<IChildProcessHandle>`

**Comment by cawhitworth** [comment]
To be fair, though, before this change it'd block for a maximum of 20
seconds before throwing an exception and after it'll block for 2 minutes.
Either way if it does take a while to start up you're going to get a
noticeable amount of time spent with an unresponsive UI.

I agree it'd be nice if AppHost dealt with this for you, but that's a
different and much bigger PR :)

**Comment by cawhitworth** [comment]
Any more for any more on this?

**Comment by GrahamTheCoder** [comment]
Nope, I was just digressing into work that needs doing on SOC, the PR is fine.

**Comment by cawhitworth** [comment]
OK, I'm merging it, then.

**Pull request merged**
